name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: gamindev/jvm-nx-dev:latest

    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build the Docker image
        uses: actions/checkout@v3
        run: docker buildx build --no-cache --progress=plain --platform linux/amd64 -t jvm-nx-dev:latest . && docker tag jvm-nx-dev:latest gamindev/jvm-nx-dev:latest && docker push gamindev/jvm-nx-dev:latest
